# Generated by Django 6.0.5 on 2026-07-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sps30Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pm1', models.PositiveSmallIntegerField()),
                ('pm25', models.PositiveSmallIntegerField()),
                ('pm4', models.PositiveSmallIntegerField()),
                ('pm10', models.PositiveSmallIntegerField()),
                ('nc0', models.PositiveSmallIntegerField()),
                ('nc1', models.PositiveSmallIntegerField()),
                ('nc25', models.PositiveSmallIntegerField()),
                ('nc4', models.PositiveSmallIntegerField()),
                ('nc10', models.PositiveSmallIntegerField()),
                ('typicalParticleSize', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
